export interface Option {
  id: 'A' | 'B' | 'C' | 'D';
  textEs: string;
  textAm: string;
}

export interface Question {
  id: number;
  letter: string; // Letter in El Rosco (A, B, C, ... Z)
  tenseCategory: 'Pretérito Perfecto' | 'Indefinido' | 'Imperfecto' | 'Pluscuamperfecto' | 'Contraste de pasados';
  tenseArmenian: string;
  situationEs: string;
  situationAm: string;
  options: Option[];
  correctOption: 'A' | 'B' | 'C' | 'D';
  explanationEs: string;
  explanationAm: string;
}

export const QUESTIONS: Question[] = [
  {
    id: 1,
    letter: 'A',
    tenseCategory: 'Pretérito Perfecto',
    tenseArmenian: 'Pretérito Perfecto (Հարակատար անցյալ)',
    situationEs: 'Estás en la biblioteca. Tu amigo pregunta: ¿Has encontrado el libro que buscabas?',
    situationAm: 'Դու գրադարանում ես։ Ընկերդ հարցնում է․ «Գտե՞լ ես այն գիրքը, որը փնտրում էիր»։',
    options: [
      { id: 'A', textEs: 'Sí, lo he encontrado en la segunda planta.', textAm: 'Այո, այն գտել եմ երկրորդ հարկում։' },
      { id: 'B', textEs: 'De pequeño leía muchos cuentos.', textAm: 'Փոքր ժամանակ շատ հեքիաթներ էի կարդում։' },
      { id: 'C', textEs: 'Ayer compré un cuaderno.', textAm: 'Երեկ տետր գնեցի։' },
      { id: 'D', textEs: 'La biblioteca era muy grande.', textAm: 'Գրադարանը շատ մեծ էր։' },
    ],
    correctOption: 'A',
    explanationEs: 'La pregunta usa Pretérito Perfecto ("¿Has encontrado...?"), por lo que la respuesta coherente en el mismo marco temporal de presente/reciente es "lo he encontrado".',
    explanationAm: 'Հարցը տրված է Pretérito Perfecto ժամանակաձևով («¿Has encontrado...?»), ուստի պատասխանը նույնպես պետք է լինի նույն ժամանակով՝ «lo he encontrado»։',
  },
  {
    id: 2,
    letter: 'B',
    tenseCategory: 'Indefinido',
    tenseArmenian: 'Indefinido (Անցյալ կատարյալ)',
    situationEs: 'Ayer fuiste al médico. Te preguntan: ¿Qué te dijo?',
    situationAm: 'Երեկ բժշկի էիր գնացել։ Հարցնում են․ «Ի՞նչ ասաց բժիշկը»։',
    options: [
      { id: 'A', textEs: 'Hoy me siento mejor.', textAm: 'Այսօր ինձ ավելի լավ եմ զգում։' },
      { id: 'B', textEs: 'Me dijo que tenía que descansar.', textAm: 'Նա ինձ ասաց, որ պետք է հանգստանամ։' },
      { id: 'C', textEs: 'Antes iba poco al médico.', textAm: 'Առաջ քիչ էի գնում բժշկի։' },
      { id: 'D', textEs: 'Ya había desayunado.', textAm: 'Արդեն նախաճաշել էի։' },
    ],
    correctOption: 'B',
    explanationEs: 'El marcador temporal es "ayer" y la pregunta es puntual en el pasado: "¿Qué te dijo?". La respuesta directa en Indefinido es "Me dijo...".',
    explanationAm: 'Գործողությունը կատարվել է երեկ («ayer») և հարցնում են կոնկրետ գործողության մասին («¿Qué te dijo?»): Ճիշտ պատասխանն է՝ «Me dijo que tenía que descansar»։',
  },
  {
    id: 3,
    letter: 'C',
    tenseCategory: 'Imperfecto',
    tenseArmenian: 'Imperfecto (Անցյալ անկատար նկարագրություն)',
    situationEs: 'Hablas de tu barrio cuando eras niño. ¿Cómo era?',
    situationAm: 'Պատմում ես քո թաղամասի մասին, երբ փոքր էիր։ «Ինչպիսի՞ն էր»։',
    options: [
      { id: 'A', textEs: 'Era tranquilo y había muchos árboles.', textAm: 'Այն խաղաղ էր և շատ ծառեր կային։' },
      { id: 'B', textEs: 'Ayer fui al centro.', textAm: 'Երեկ կենտրոն գնացի։' },
      { id: 'C', textEs: 'Hoy he visto a un vecino.', textAm: 'Այսօր մի հարևանի եմ տեսել։' },
      { id: 'D', textEs: 'El sábado abrió una tienda.', textAm: 'Շաբաթ օրը մի խանութ բացվեց։' },
    ],
    correctOption: 'A',
    explanationEs: 'Para describir lugares, situaciones y estados en el pasado se usa el Pretérito Imperfecto: "era tranquilo y había...".',
    explanationAm: 'Անցյալում տեղանքի, վիճակի նկարագրության համար օգտագործվում է Imperfecto ժամանակաձևը՝ «Era tranquilo y había muchos árboles»։',
  },
  {
    id: 4,
    letter: 'D',
    tenseCategory: 'Pluscuamperfecto',
    tenseArmenian: 'Pluscuamperfecto (Վաղակատար անցյալ)',
    situationEs: 'Llegaste al aeropuerto y descubriste que el avión ya había despegado.',
    situationAm: 'Հասար օդանավակայան և պարզեցիր, որ ինքնաթիռն արդեն մեկնել էր։',
    options: [
      { id: 'A', textEs: 'El aeropuerto estaba lleno de gente.', textAm: 'Օդանավակայանը լիքն էր մարդկանցով։' },
      { id: 'B', textEs: 'He comprado un billete hoy.', textAm: 'Այսօր տոմս եմ գնել։' },
      { id: 'C', textEs: 'Cuando llegué, el avión ya había despegado.', textAm: 'Երբ հասա, ինքնաթիռն արդեն մեկնել (թռել) էր։' },
      { id: 'D', textEs: 'Siempre llegaba temprano.', textAm: 'Միշտ շուտ էի հասնում։' },
    ],
    correctOption: 'C',
    explanationEs: 'Pluscuamperfecto ("ya había despegado") indica una acción anterior a otra acción en el pasado ("cuando llegué").',
    explanationAm: 'Pluscuamperfecto-ն («ya había despegado») ցույց է տալիս գործողություն, որն ավարտվել էր մինչև մեկ այլ անցյալ գործողություն («cuando llegué»)։',
  },
  {
    id: 5,
    letter: 'E',
    tenseCategory: 'Pretérito Perfecto',
    tenseArmenian: 'Pretérito Perfecto (Այս շաբաթվա ժամանակահատված)',
    situationEs: 'Tu profesor pregunta: ¿Has estudiado para el examen de esta semana?',
    situationAm: 'Ուսուցիչը հարցնում է․ «Այս շաբաթվա քննության համար սովորե՞լ ես»։',
    options: [
      { id: 'A', textEs: 'Sí, esta semana he estudiado bastante.', textAm: 'Այո, այս շաբաթ բավականին սովորել եմ։' },
      { id: 'B', textEs: 'Ayer fui al cine.', textAm: 'Երեկ կինոթատրոն գնացի։' },
      { id: 'C', textEs: 'Cuando era pequeño estudiaba por la mañana.', textAm: 'Երբ փոքր էի, առավոտյան էի սովորում։' },
      { id: 'D', textEs: 'El examen fue difícil el año pasado.', textAm: 'Անցյալ տարի քննությունը դժվար էր։' },
    ],
    correctOption: 'A',
    explanationEs: '"Esta semana" es un período temporal no terminado que exige Pretérito Perfecto: "esta semana he estudiado".',
    explanationAm: '«Esta semana»-ն (այս շաբաթ) դեռ չավարտված ժամանակահատված է, որը պահանջում է Pretérito Perfecto՝ «he estudiado»։',
  },
  {
    id: 6,
    letter: 'F',
    tenseCategory: 'Contraste de pasados',
    tenseArmenian: 'Contraste (Imperfecto + Indefinido - Ընդհատված գործողություն)',
    situationEs: 'El sábado se fue la luz mientras preparabas la cena. ¿Qué pasó?',
    situationAm: 'Շաբաթ օրը, երբ ընթրիքն էիր պատրաստում, հոսանքն անջատվեց։ Ի՞նչ պատահեց։',
    options: [
      { id: 'A', textEs: 'Hoy he cocinado pasta.', textAm: 'Այսօր մակարոնեղեն եմ եփել։' },
      { id: 'B', textEs: 'Mientras cocinaba, se fue la luz.', textAm: 'Մինչ ես եփում էի, լույսն անջատվեց։' },
      { id: 'C', textEs: 'Antes había cenado a las ocho.', textAm: 'Նախկինում ես ընթրում էի ութին։' },
      { id: 'D', textEs: 'Siempre preparo la cena temprano.', textAm: 'Միշտ ընթրիքը շուտ եմ պատրաստում։' },
    ],
    correctOption: 'B',
    explanationEs: 'Acción en progreso en el pasado (mientras cocinaba - Imperfecto) interrumpida por una acción puntual (se fue la luz - Indefinido).',
    explanationAm: 'Ընթացքի մեջ գտնվող գործողությունը («mientras cocinaba» - Imperfecto) ընդհատվում է կարճատև ավարտուն գործողությամբ («se fue la luz» - Indefinido)։',
  },
  {
    id: 7,
    letter: 'G',
    tenseCategory: 'Indefinido',
    tenseArmenian: 'Indefinido (Երեկվա ավարտված գործողություն)',
    situationEs: 'Tu amiga pregunta: ¿Qué compraste ayer en el mercado?',
    situationAm: 'Ընկերուհիդ հարցնում է․ «Երեկ շուկայում ի՞նչ գնեցիր»։',
    options: [
      { id: 'A', textEs: 'He comprado fruta esta semana.', textAm: 'Այս շաբաթ միրգ եմ գնել։' },
      { id: 'B', textEs: 'Compré tomates, queso y pan.', textAm: 'Գնեցի լոլիկ, պանիր և հաց։' },
      { id: 'C', textEs: 'De pequeño iba al mercado con mi abuelo.', textAm: 'Փոքր ժամանակ պապիկիս հետ էի գնում շուկա։' },
      { id: 'D', textEs: 'Ya había preparado la comida.', textAm: 'Արդեն պատրաստել էի կերակուրը։' },
    ],
    correctOption: 'B',
    explanationEs: 'Con el marcador temporal "ayer" se usa el Pretérito Indefinido: "compré tomates, queso y pan".',
    explanationAm: '«Ayer» (երեկ) ժամանակացույցի հետ օգտագործվում է Indefinido ժամանակաձևը՝ «Compré...»։',
  },
  {
    id: 8,
    letter: 'H',
    tenseCategory: 'Pluscuamperfecto',
    tenseArmenian: 'Pluscuamperfecto (Գործողություն մինչև ժամանումը)',
    situationEs: 'Llegaste a casa y no encontraste a nadie. Después supiste que todos habían salido.',
    situationAm: 'Տուն հասար և ոչ ոքի չգտար։ Հետո իմացար, որ բոլորը արդեն դուրս էին եկել։',
    options: [
      { id: 'A', textEs: 'Todos salen los viernes.', textAm: 'Բոլորը դուրս են գալիս ուրբաթ օրերին։' },
      { id: 'B', textEs: 'Esta semana hemos salido mucho.', textAm: 'Այս շաբաթ մենք շատ ենք դուրս եկել։' },
      { id: 'C', textEs: 'Cuando llegué, todos ya habían salido.', textAm: 'Երբ ես տուն հասա, բոլորն արդեն դուրս էին եկել։' },
      { id: 'D', textEs: 'Ayer la casa era tranquila.', textAm: 'Երեկ տունը հանգիստ էր։' },
    ],
    correctOption: 'C',
    explanationEs: 'La acción de salir ocurrió antes del momento de llegar: "Cuando llegué (Indefinido), todos ya habían salido (Pluscuamperfecto)".',
    explanationAm: 'Տուն հասնելուց («llegué») առաջ բոլորն արդեն դուրս էին եկել («ya habían salido» - Pluscuamperfecto)։',
  },
  {
    id: 9,
    letter: 'I',
    tenseCategory: 'Imperfecto',
    tenseArmenian: 'Imperfecto (Կրկնվող սովորություն անցյալում)',
    situationEs: 'Te preguntan: ¿Cómo pasabas las tardes durante las vacaciones de verano?',
    situationAm: 'Հարցնում են․ «Ամառային արձակուրդներին ինչպե՞ս էիր անցկացնում կեսօրները»։',
    options: [
      { id: 'A', textEs: 'Ayer nadé una hora.', textAm: 'Երեկ մեկ ժամ լողացի։' },
      { id: 'B', textEs: 'Normalmente iba a la playa y jugaba con mis primos.', textAm: 'Սովորաբար գնում էի լողափ և խաղում զարմիկներիս հետ։' },
      { id: 'C', textEs: 'Hoy he descansado en casa.', textAm: 'Այսօր տանը հանգստացել եմ։' },
      { id: 'D', textEs: 'Ya había vuelto del viaje.', textAm: 'Արդեն վերադարձել էի ճամփորդությունից։' },
    ],
    correctOption: 'B',
    explanationEs: 'Para hábitos y rutinas en el pasado con marcadores como "normalmente" se utiliza el Pretérito Imperfecto: "iba y jugaba".',
    explanationAm: 'Անցյալում կրկնվող սովորությունների և առօրյայի համար («normalmente») օգտագործվում է Imperfecto՝ «iba y jugaba»։',
  },
  {
    id: 10,
    letter: 'J',
    tenseCategory: 'Pretérito Perfecto',
    tenseArmenian: 'Pretérito Perfecto (Այսօրվա իրադարձություն)',
    situationEs: 'Hoy has perdido el móvil durante unos minutos. Tu amigo pregunta qué ha pasado.',
    situationAm: 'Այսօր մի քանի րոպեով կորցրել ես հեռախոսդ։ Ընկերդ հարցնում է՝ ի՞նչ է պատահել։',
    options: [
      { id: 'A', textEs: 'He dejado el móvil en una cafetería, pero ya lo he recuperado.', textAm: 'Հեռախոսս սրճարանում էի թողել, բայց արդեն հետ եմ վերցրել։' },
      { id: 'B', textEs: 'Cuando era niño no tenía móvil.', textAm: 'Երբ փոքր էի, հեռախոս չունեի։' },
      { id: 'C', textEs: 'Ayer compré una funda.', textAm: 'Երեկ պատյան գնեցի։' },
      { id: 'D', textEs: 'Antes llamaba desde casa.', textAm: 'Առաջ տանից էի զանգահարում։' },
    ],
    correctOption: 'A',
    explanationEs: 'El marcador "hoy" pertenece al presente y exige Pretérito Perfecto: "he dejado... he recuperado".',
    explanationAm: '«Hoy» (այսօր) բառը պատկանում է ներկա ժամանակահատվածին և պահանջում է Pretérito Perfecto՝ «he dejado... ya lo he recuperado»։',
  },
  {
    id: 11,
    letter: 'K',
    tenseCategory: 'Indefinido',
    tenseArmenian: 'Indefinido (Երեկվա տպավորություն / գնահատական)',
    situationEs: 'Ayer viste una exposición en un museo. ¿Qué te pareció?',
    situationAm: 'Երեկ թանգարանում ցուցահանդես տեսար։ «Ինչպիսի՞ն էր»։',
    options: [
      { id: 'A', textEs: 'El museo abre a las diez.', textAm: 'Թանգարանը բացվում է ժամը տասին։' },
      { id: 'B', textEs: 'La exposición fue muy interesante.', textAm: 'Ցուցահանդեսը շատ հետաքրքիր էր։' },
      { id: 'C', textEs: 'Hoy he leído un libro.', textAm: 'Այսօր գիրք եմ կարդացել։' },
      { id: 'D', textEs: 'Cuando era pequeño dibujaba mucho.', textAm: 'Երբ փոքր էի, շատ էի նկարում։' },
    ],
    correctOption: 'B',
    explanationEs: 'Para valorar un evento finalizado en el pasado ("ayer") usamos Indefinido: "La exposición fue muy interesante".',
    explanationAm: 'Երեկվա («ayer») ավարտված իրադարձությունը գնահատելիս օգտագործում ենք Indefinido՝ «fue muy interesante»։',
  },
  {
    id: 12,
    letter: 'L',
    tenseCategory: 'Contraste de pasados',
    tenseArmenian: 'Contraste (Indefinido + Estar + Gerundio / Imperfecto)',
    situationEs: 'Llegaste al hotel y tu habitación todavía no estaba preparada. ¿Qué explicas?',
    situationAm: 'Հասար հյուրանոց, բայց սենյակը դեռ պատրաստ չէր։ Ի՞նչ ես պատմում։',
    options: [
      { id: 'A', textEs: 'La habitación era grande.', textAm: 'Սենյակը մեծ էր։' },
      { id: 'B', textEs: 'Cuando llegué, todavía estaban preparando la habitación.', textAm: 'Երբ ես հասա, դեռ սենյակն էին պատրաստում։' },
      { id: 'C', textEs: 'Ya había dormido allí dos veces.', textAm: 'Արդեն երկու անգամ քնել էի այնտեղ։' },
      { id: 'D', textEs: 'Hoy he reservado otro hotel.', textAm: 'Այսօր ուրիշ հյուրանոց եմ ամրագրել։' },
    ],
    correctOption: 'B',
    explanationEs: 'El momento puntual de llegada ("cuando llegué" - Indefinido) coincide con una acción en desarrollo ("estaban preparando" - Imperfecto continuo).',
    explanationAm: 'Ժամանելու պահին («cuando llegué» - Indefinido) գործողությունը դեռ ընթացքի մեջ էր («estaban preparando» - Imperfecto)։',
  },
  {
    id: 13,
    letter: 'M',
    tenseCategory: 'Pretérito Perfecto',
    tenseArmenian: 'Pretérito Perfecto (Այս ամիս փորձառություն)',
    situationEs: 'Tu amigo pregunta: ¿Has probado alguna comida nueva este mes?',
    situationAm: 'Ընկերդ հարցնում է․ «Այս ամիս որևէ նոր ուտեստ փորձե՞լ ես»։',
    options: [
      { id: 'A', textEs: 'Sí, he probado dos platos nuevos.', textAm: 'Այո, երկու նոր ճաշատեսակ եմ փորձել։' },
      { id: 'B', textEs: 'Ayer cocinaba cuando llamó Ana.', textAm: 'Երեկ ճաշ էի եփում, երբ Անան զանգեց։' },
      { id: 'C', textEs: 'Cuando era niño no comía pescado.', textAm: 'Երբ փոքր էի, ձուկ չէի ուտում։' },
      { id: 'D', textEs: 'El año pasado fui a Italia.', textAm: 'Անցյալ տարի Իտալիա գնացի։' },
    ],
    correctOption: 'A',
    explanationEs: 'Para experiencias vitales dentro de un tiempo no concluido ("este mes") se usa Pretérito Perfecto: "he probado".',
    explanationAm: '«Este mes» (այս ամիս) չավարտված ժամանակում փորձառության մասին խոսելիս գործածվում է Pretérito Perfecto՝ «he probado»։',
  },
  {
    id: 14,
    letter: 'N',
    tenseCategory: 'Imperfecto',
    tenseArmenian: 'Imperfecto (Միշտ կրկնվող գործողություն)',
    situationEs: 'Te preguntan qué hacías siempre antes de un examen.',
    situationAm: 'Հարցնում են՝ քննությունից առաջ սովորաբար ի՞նչ էիր անում։',
    options: [
      { id: 'A', textEs: 'Repasaba mis apuntes y preparaba todo la noche anterior.', textAm: 'Կրկնում էի նշումներս և ամեն ինչ պատրաստում նախորդ գիշերը։' },
      { id: 'B', textEs: 'Ayer hice un examen.', textAm: 'Երեկ քննություն հանձնեցի։' },
      { id: 'C', textEs: 'Hoy he hablado con el profesor.', textAm: 'Այսօր խոսել եմ դասախոսի հետ։' },
      { id: 'D', textEs: 'Ya había terminado el examen.', textAm: 'Արդեն ավարտել էի քննությունը։' },
    ],
    correctOption: 'A',
    explanationEs: '"Siempre" y "hacías" expresan hábitos constantes en el pasado, lo que corresponde al Imperfecto: "repasaba... y preparaba...".',
    explanationAm: '«Siempre» (միշտ) բառը ցույց է տալիս անցյալի կրկնվող սովորույթ, ուստի պահանջում է Imperfecto՝ «repasaba... y preparaba...»։',
  },
  {
    id: 15,
    letter: 'Ñ',
    tenseCategory: 'Pluscuamperfecto',
    tenseArmenian: 'Pluscuamperfecto (Գործողություն նախքան մեկնելը)',
    situationEs: 'Te preguntan: ¿Qué habías hecho antes de salir de viaje?',
    situationAm: 'Հարցնում են․ «Ի՞նչ էիր արել մինչև ճանապարհորդության մեկնելը»։',
    options: [
      { id: 'A', textEs: 'Había preparado la maleta y había cerrado todas las ventanas.', textAm: 'Պատրաստել էի ճամպրուկը և փակել էի բոլոր պատուհանները։' },
      { id: 'B', textEs: 'Viajo dos veces al año.', textAm: 'Տարին երկու անգամ եմ ճանապարհորդում։' },
      { id: 'C', textEs: 'Ayer llegué a las seis.', textAm: 'Երեկ հասա ժամը վեցին։' },
      { id: 'D', textEs: 'Este mes he comprado una mochila.', textAm: 'Այս ամիս ուսապարկ եմ գնել։' },
    ],
    correctOption: 'A',
    explanationEs: 'La pregunta está formulada en Pluscuamperfecto ("¿Qué habías hecho...?"), por lo que la respuesta coherente es "Había preparado... y había cerrado...".',
    explanationAm: 'Հարցը Pluscuamperfecto ժամանակով է («¿Qué habías hecho...?»), հետևաբար ճիշտ պատասխանը նույնպես Pluscuamperfecto է՝ «Había preparado...»։',
  },
  {
    id: 16,
    letter: 'O',
    tenseCategory: 'Imperfecto',
    tenseArmenian: 'Imperfecto (Անցյալի անձի բնութագիր)',
    situationEs: 'Hablas de un profesor que tenías hace años.',
    situationAm: 'Պատմում ես մի ուսուցչի մասին, որը տարիներ առաջ ունեիր։',
    options: [
      { id: 'A', textEs: 'Era exigente, pero explicaba muy bien.', textAm: 'Պահանջկոտ էր, բայց շատ լավ էր բացատրում։' },
      { id: 'B', textEs: 'Ayer me escribió un mensaje.', textAm: 'Երեկ նա ինձ նամակ գրեց։' },
      { id: 'C', textEs: 'Esta semana he estudiado mucho.', textAm: 'Այս շաբաթ ես շատ եմ սովորել։' },
      { id: 'D', textEs: 'El examen terminó a las once.', textAm: 'Քննությունն ավարտվեց տասնմեկին։' },
    ],
    correctOption: 'A',
    explanationEs: 'Para describir el carácter o la forma de ser de una persona en el pasado usamos Imperfecto: "Era exigente, pero explicaba bien".',
    explanationAm: 'Անցյալում մարդու բնավորությունը կամ հատկանիշները նկարագրելու համար օգտագործում ենք Imperfecto՝ «Era exigente, pero explicaba muy bien»։',
  },
  {
    id: 17,
    letter: 'P',
    tenseCategory: 'Contraste de pasados',
    tenseArmenian: 'Contraste (Վարելիս սկսեց ձյուն գալ)',
    situationEs: 'Ayer empezó a nevar cuando estabas conduciendo.',
    situationAm: 'Երեկ սկսեց ձյուն գալ, երբ մեքենա էիր վարում։',
    options: [
      { id: 'A', textEs: 'Ayer conduje durante cinco horas.', textAm: 'Երեկ հինգ ժամ մեքենա վարեցի։' },
      { id: 'B', textEs: 'Mientras conducía, empezó a nevar.', textAm: 'Երբ մեքենա էի վարում, սկսեց ձյուն գալ։' },
      { id: 'C', textEs: 'Hoy ha hecho buen tiempo.', textAm: 'Այսօր լավ եղանակ է եղել։' },
      { id: 'D', textEs: 'Ya había aparcado el coche mañana.', textAm: 'Արդեն մեքենան կայանել էի վաղը։' },
    ],
    correctOption: 'B',
    explanationEs: 'Acción duradera de fondo (mientras conducía - Imperfecto) combinada con el inicio repentino de otra acción (empezó a nevar - Indefinido).',
    explanationAm: 'Երկարատև ֆոնային գործողությունը («mientras conducía» - Imperfecto) զուգակցվում է նոր գործողության հանկարծակի սկզբի հետ («empezó a nevar» - Indefinido)։',
  },
  {
    id: 18,
    letter: 'Q',
    tenseCategory: 'Contraste de pasados',
    tenseArmenian: 'Contraste (Imperfecto + Pluscuamperfecto)',
    situationEs: 'Ayer viste a alguien correr porque había perdido el autobús.',
    situationAm: 'Երեկ տեսար մեկին վազելիս, որովհետև նա ավտոբուսը բաց էր թողել։',
    options: [
      { id: 'A', textEs: 'Corría porque había perdido el autobús.', textAm: 'Վազում էր, որովհետև ավտոբուսը բաց էր թողել։' },
      { id: 'B', textEs: 'Hoy he tomado el autobús.', textAm: 'Այսօր ավտոբուս եմ նստել։' },
      { id: 'C', textEs: 'Cuando era niño corría mucho.', textAm: 'Երբ փոքր էի, շատ էի վազում։' },
      { id: 'D', textEs: 'Mañana saldrá temprano.', textAm: 'Վաղը շուտ դուրս կգա։' },
    ],
    correctOption: 'A',
    explanationEs: '"Corría" describe la acción en desarrollo en ese momento del pasado, y "había perdido" es la causa anterior que motivó la carrera.',
    explanationAm: '«Corría» (վազում էր) նկարագրում է անցյալի գործողության ընթացքը, իսկ «había perdido»-ն՝ դրան նախորդած պատճառը (ավտոբուսը բաց թողնելը)։',
  },
  {
    id: 19,
    letter: 'R',
    tenseCategory: 'Pluscuamperfecto',
    tenseArmenian: 'Pluscuamperfecto (Խանութն արդեն փակել էին)',
    situationEs: 'Llegaste a una tienda, pero ya la habían cerrado.',
    situationAm: 'Հասար խանութ, բայց այն արդեն փակել էին։',
    options: [
      { id: 'A', textEs: 'La tienda era pequeña.', textAm: 'Խանութը փոքր էր։' },
      { id: 'B', textEs: 'Cuando llegué, ya habían cerrado la tienda.', textAm: 'Երբ ես հասա, խանութն արդեն փակել էին։' },
      { id: 'C', textEs: 'Hoy he comprado una camisa.', textAm: 'Այսօր վերնաշապիկ եմ գնել։' },
      { id: 'D', textEs: 'Siempre cerraban a las diez.', textAm: 'Միշտ փակում էին ժամը տասին։' },
    ],
    correctOption: 'B',
    explanationEs: 'La acción de cerrar la tienda precedió a la llegada: "Cuando llegué (Indefinido), ya habían cerrado la tienda (Pluscuamperfecto)".',
    explanationAm: 'Խանութը փակելու գործողությունը նախորդել էր հասնելու պահին՝ «Cuando llegué... ya habían cerrado la tienda»։',
  },
  {
    id: 20,
    letter: 'S',
    tenseCategory: 'Imperfecto',
    tenseArmenian: 'Imperfecto (Մանկության սովորույթ)',
    situationEs: 'Te preguntan: ¿Qué hacías normalmente antes de dormir cuando eras niño?',
    situationAm: 'Հարցնում են․ «Երբ փոքր էիր, սովորաբար ի՞նչ էիր անում քնելուց առաջ»։',
    options: [
      { id: 'A', textEs: 'Leía un cuento y después apagaba la luz.', textAm: 'Հեքիաթ էի կարդում, իսկ հետո անջատում լույսը։' },
      { id: 'B', textEs: 'Ayer terminé un libro.', textAm: 'Երեկ ավարտեցի մի գիրք։' },
      { id: 'C', textEs: 'Hoy he dormido ocho horas.', textAm: 'Այսօր ութ ժամ եմ քնել։' },
      { id: 'D', textEs: 'Ya había cerrado la puerta.', textAm: 'Արդեն դուռը փակել էի։' },
    ],
    correctOption: 'A',
    explanationEs: 'Rutinas repetitivas de la infancia se relatan en Pretérito Imperfecto: "Leía un cuento y después apagaba la luz".',
    explanationAm: 'Մանկության կրկնվող սովորությունների համար օգտագործվում է Imperfecto՝ «Leía un cuento y después apagaba la luz»։',
  },
  {
    id: 21,
    letter: 'T',
    tenseCategory: 'Pretérito Perfecto',
    tenseArmenian: 'Pretérito Perfecto (Այսօրվա խաղի արդյունք)',
    situationEs: 'Hoy tu equipo ha jugado un partido. Un amigo pregunta: ¿Cómo ha ido?',
    situationAm: 'Այսօր քո թիմը խաղ է խաղացել։ Ընկերդ հարցնում է․ «Ինչպե՞ս անցավ»։',
    options: [
      { id: 'A', textEs: 'Hemos jugado bien y hemos marcado dos goles.', textAm: 'Լավ ենք խաղացել և երկու գոլ ենք խփել։' },
      { id: 'B', textEs: 'Cuando era pequeño entrenaba mucho.', textAm: 'Երբ փոքր էի, շատ էի մարզվում։' },
      { id: 'C', textEs: 'El año pasado perdimos un partido.', textAm: 'Անցյալ տարի մենք մի խաղ պարտվեցինք։' },
      { id: 'D', textEs: 'Antes del partido había llovido.', textAm: 'Խաղից առաջ անձրև էր եկել։' },
    ],
    correctOption: 'A',
    explanationEs: 'La acción ocurrió "hoy" y la pregunta es "¿Cómo ha ido?". La respuesta adecuada es en Pretérito Perfecto: "Hemos jugado... hemos marcado...".',
    explanationAm: 'Խաղը տեղի է ունեցել այսօր («hoy») և հարցնում են՝ «¿Cómo ha ido?»: Ճիշտ պատասխանը Pretérito Perfecto է՝ «Hemos jugado... y hemos marcado...»։',
  },
  {
    id: 22,
    letter: 'U',
    tenseCategory: 'Contraste de pasados',
    tenseArmenian: 'Contraste (Indefinido + Pluscuamperfecto)',
    situationEs: 'Ayer entraste en un restaurante y reconociste al camarero porque ya lo habías visto antes.',
    situationAm: 'Երեկ ռեստորան մտար և ճանաչեցիր մատուցողին, որովհետև նախկինում արդեն տեսել էիր նրան։',
    options: [
      { id: 'A', textEs: 'El camarero trabaja allí ahora.', textAm: 'Մատուցողն այժմ աշխատում է այնտեղ։' },
      { id: 'B', textEs: 'Lo reconocí porque ya lo había visto antes.', textAm: 'Ես նրան ճանաչեցի, որովհետև նախկինում արդեն տեսել էի։' },
      { id: 'C', textEs: 'Hoy he comido en casa.', textAm: 'Այսօր տանն եմ կերել։' },
      { id: 'D', textEs: 'Cuando era niño no iba a restaurantes.', textAm: 'Երբ փոքր էի, ռեստորաններ չէի գնում։' },
    ],
    correctOption: 'B',
    explanationEs: 'El acto puntual de reconocer (Indefinido: "lo reconocí") se debe a una experiencia anterior (Pluscuamperfecto: "ya lo había visto").',
    explanationAm: 'Ճանաչելու կոնկրետ գործողությունը (Indefinido՝ «lo reconocí») հիմնված է նախկինում տեսած լինելու փաստի վրա (Pluscuamperfecto՝ «ya lo había visto»)։',
  },
  {
    id: 23,
    letter: 'V',
    tenseCategory: 'Indefinido',
    tenseArmenian: 'Indefinido (Երկու տարի առաջվա կոնկրետ ճամփորդություն)',
    situationEs: 'Te preguntan por un viaje concreto de hace dos años.',
    situationAm: 'Հարցնում են երկու տարի առաջվա կոնկրետ ճանապարհորդության մասին։',
    options: [
      { id: 'A', textEs: 'Hace dos años viajé a Valencia con mi familia.', textAm: 'Երկու տարի առաջ ընտանիքիս հետ ճանապարհորդեցի Վալենսիա։' },
      { id: 'B', textEs: 'Este año he viajado dos veces.', textAm: 'Այս տարի երկու անգամ եմ ճանապարհորդել։' },
      { id: 'C', textEs: 'Cuando era niño viajaba en verano.', textAm: 'Երբ փոքր էի, ամռանն էի ճանապարհորդում։' },
      { id: 'D', textEs: 'Antes de viajar ya había comprado una maleta.', textAm: 'Ճանապարհորդելուց առաջ արդեն ճամպրուկ էի գնել։' },
    ],
    correctOption: 'A',
    explanationEs: 'El marcador "hace dos años" señala un tiempo cerrado y puntual que exige Pretérito Indefinido: "viajé a Valencia".',
    explanationAm: '«Hace dos años» (երկու տարի առաջ) ցույց է տալիս անցյալի կոնկրետ ավարտված պահ, ուստի օգտագործվում է Indefinido՝ «viajé»։',
  },
  {
    id: 24,
    letter: 'W',
    tenseCategory: 'Contraste de pasados',
    tenseArmenian: 'Contraste (Imperfecto + Indefinido - Դուռը թակեցին)',
    situationEs: 'Estabas estudiando cuando alguien llamó a la puerta.',
    situationAm: 'Դու սովորում էիր, երբ ինչ-որ մեկը դուռը թակեց։',
    options: [
      { id: 'A', textEs: 'He estudiado mucho esta semana.', textAm: 'Այս շաբաթ շատ եմ սովորել։' },
      { id: 'B', textEs: 'Mientras estudiaba, alguien llamó a la puerta.', textAm: 'Երբ ես սովորում էի, ինչ-որ մեկը թակեց դուռը։' },
      { id: 'C', textEs: 'Ayer estudié tres horas y después cené.', textAm: 'Երեկ սովորեցի երեք ժամ և հետո ընթրեցի։' },
      { id: 'D', textEs: 'Ya había abierto la puerta.', textAm: 'Արդեն բացել էի դուռը։' },
    ],
    correctOption: 'B',
    explanationEs: 'La acción en desarrollo "mientras estudiaba" (Imperfecto) es interrumpida por la llamada puntual "alguien llamó" (Indefinido).',
    explanationAm: 'Սովորելու ընթացքի մեջ գտնվող գործողությունը («mientras estudiaba» - Imperfecto) ընդհատվում է դուռը թակելով («alguien llamó» - Indefinido)։',
  },
  {
    id: 25,
    letter: 'X',
    tenseCategory: 'Pretérito Perfecto',
    tenseArmenian: 'Pretérito Perfecto (Ամբողջ տարվա ընթացքում չտեսնելը)',
    situationEs: 'Hoy encuentras a un amigo que no has visto en todo el año. ¿Qué dices?',
    situationAm: 'Այսօր հանդիպում ես ընկերոջդ, որին ամբողջ տարին չես տեսել։ Ի՞նչ ես ասում։',
    options: [
      { id: 'A', textEs: '¡Cuánto tiempo! No te he visto en todo el año.', textAm: '«Որքա՜ն ժամանակ է։ Ամբողջ տարին քեզ չեմ տեսել»։' },
      { id: 'B', textEs: 'Ayer jugábamos al fútbol.', textAm: 'Երեկ ֆուտբոլ էինք խաղում։' },
      { id: 'C', textEs: 'De pequeño tenía muchos amigos.', textAm: 'Փոքր ժամանակ շատ ընկերներ ունեի։' },
      { id: 'D', textEs: 'Ya había salido antes de verte.', textAm: 'Արդեն դուրս էի եկել նախքան քեզ տեսնելը։' },
    ],
    correctOption: 'A',
    explanationEs: '"En todo el año" es un período temporal aún en curso, por lo que se utiliza el Pretérito Perfecto: "No te he visto".',
    explanationAm: '«En todo el año» (ամբողջ տարին) դեռ շարունակվող ժամանակահատված է, ուստի կիրառվում է Pretérito Perfecto՝ «No te he visto»։',
  },
  {
    id: 26,
    letter: 'Y',
    tenseCategory: 'Contraste de pasados',
    tenseArmenian: 'Contraste (Indefinido + Pluscuamperfecto - Գրիչը մոռացել էիր)',
    situationEs: 'Antes de empezar el examen, te diste cuenta de que habías olvidado un bolígrafo.',
    situationAm: 'Քննությունը սկսելուց առաջ հասկացար, որ գրիչդ մոռացել էիր։',
    options: [
      { id: 'A', textEs: 'Hoy he comprado tres bolígrafos.', textAm: 'Այսօր երեք գրիչ եմ գնել։' },
      { id: 'B', textEs: 'Antes del examen me di cuenta de que había olvidado el bolígrafo.', textAm: 'Քննությունից առաջ հասկացա, որ մոռացել էի գրիչս։' },
      { id: 'C', textEs: 'Cuando era niño escribía con lápiz.', textAm: 'Երբ փոքր էի, մատիտով էի գրում։' },
      { id: 'D', textEs: 'El examen fue fácil.', textAm: 'Քննությունը հեշտ էր։' },
    ],
    correctOption: 'B',
    explanationEs: 'Darse cuenta ocurre en un momento puntual (me di cuenta - Indefinido), pero el olvido ocurrió con anterioridad (había olvidado - Pluscuamperfecto).',
    explanationAm: 'Գիտակցելու պահը կոնկրետ է (Indefinido՝ «me di cuenta»), սակայն գրիչը մոռանալը տեղի էր ունեցել դրանից առաջ (Pluscuamperfecto՝ «había olvidado»)։',
  },
  {
    id: 27,
    letter: 'Z',
    tenseCategory: 'Pluscuamperfecto',
    tenseArmenian: 'Pluscuamperfecto (Քնելուց առաջ արված գործողություններ)',
    situationEs: 'Te preguntan: ¿Qué habías hecho antes de acostarte anoche?',
    situationAm: 'Հարցնում են․ «Երեկ գիշեր քնելուց առաջ ի՞նչ էիր արել»։',
    options: [
      { id: 'A', textEs: 'Había preparado la ropa y había puesto el móvil a cargar.', textAm: 'Պատրաստել էի հագուստը և հեռախոսը դրել էի լիցքավորման։' },
      { id: 'B', textEs: 'Hoy he desayunado temprano.', textAm: 'Այսօր շուտ եմ նախաճաշել։' },
      { id: 'C', textEs: 'De niño dormía mucho.', textAm: 'Փոքր ժամանակ շատ էի քնում։' },
      { id: 'D', textEs: 'Ayer fui al supermercado.', textAm: 'Երեկ սուպերմարկետ գնացի։' },
    ],
    correctOption: 'A',
    explanationEs: 'Acciones realizadas antes de acostarse requieren Pluscuamperfecto: "Había preparado la ropa y había puesto el móvil a cargar".',
    explanationAm: 'Քնելուն նախորդած գործողությունները արտահայտվում են Pluscuamperfecto ժամանակով՝ «Había preparado... y había puesto...»։',
  },
];
